version: "3.8"

services:
  tank-exporter:
    image: dominikrobert/tank-exporter:v0.9.0-amd64
    container_name: tank-exporter
    restart: unless-stopped
    environment:
      - LATITUDE=51.575710
      - LONGITUDE=7.209179
      - APIKEY=YOUR_API_KEY
      - RADIUS=5
    ports:
      - "2112:2112" 
