global:
  scrape_interval: 5m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "tankerkoenig"
    static_configs:
      - targets:
          - "localhost:2112"
